version: '3'

services:
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - frontend_some-net
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    networks:
      - frontend_some-net
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - frontend_some-net
    volumes:
      - node_modules:/Bank-user/frontend/node_modules
    env_file:
      - ./.env

networks:
  frontend_some-net:
       driver: bridge

volumes:
  db-data:
  node_modules:
