# Generated by Django 4.2.10 on 2024-02-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("bank_name", models.CharField(max_length=100)),
                ("routing_number", models.CharField(max_length=100)),
                ("swift_bic", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("username", models.CharField(max_length=60)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=50)),
                (
                    "banks",
                    models.ManyToManyField(
                        blank=True, related_name="users", to="myapp.bank"
                    ),
                ),
            ],
        ),
    ]
